# Generated by Django 5.1.4 on 2025-01-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp',
            name='pm25_alarm_threshold',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
